package com.example

import org.mikrograd.core.printComputeGraph
import org.mikrograd.diff.ksp.Mikrograd

/**
 * Define experssion as function, which will be annotated to exprGenerated by KSP
 */
@Mikrograd
fun expr() {
    3.0 * 4.0 + (7.0 + 3.0)
}

fun main() {
    val ex = exprGenerated()
    println(printComputeGraph(ex))
    println(ex.evaluate())
    assert(ex.evaluate() == 12.0)
}
